{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template-python-package.name" . }}
  namespace: {{ include "template-python-package.namespace" . }}
  labels:
    {{- include "template-python-package.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
