{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template-python-package.name" . }}
  namespace: {{ include "template-python-package.namespace" . }}
  labels:
    {{- include "template-python-package.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
