name: Run Python Linters and Tests

on:
  # Trigger on PRs
  pull_request:
    branches:
      - main
  # And on pushes to main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configuring developer tools
        run: |
          make create-venv
          eval "$(make venv)"
          make setup

      - name: Run linters
        run: |
          eval "$(make venv)"
          make lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configuring developer tools
        run: |
          make create-venv
          eval "$(make venv)"
          make setup

      - name: Run tests
        run: |
          eval "$(make venv)"
          pytest tests
