name: Publish to PyPI

on:
  # Trigger only on v0.* tag pushes
  push:
    tags:
      - "v0.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    # disable the workflow by default
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: python
        run: |
          make create-venv
          eval "$(make venv)"
          make install

      - name: Run tests
        working-directory: python
        run: |
          eval "$(make venv)"
          pytest tests

      - name: Set the correct (tag) version
        working-directory: python
        run: |
          scripts/detect-and-set-tag-version.bash

      - name: Build
        working-directory: python
        run: |
          eval "$(make venv)"
          make build

      - name: Publish package to test repository
        env:
          TESTPYPI_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        working-directory: python
        run: |
          eval "$(make venv)"
          make publish-test

      - name: Publish package
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        working-directory: python
        run: |
          eval "$(make venv)"
          make publish

      - name: Waiting 30 seconds for the PyPI indexes to be updated
        run: sleep 30

      - name: Verify package install from PyPI
        working-directory: python
        run: |
          make publish-verify
